<?php

/**
 * @file os2web_old_nodes.module
 *
 * Adds a tab to a user account to show users old nodes.
 */

include_once('os2web_old_nodes.features.inc');

/**
 * Implements hook_menu();
 */
function os2web_old_nodes_menu() {
  $items = array();
  $items['user/%user/old-nodes'] = array(
    'title'            => t('Dine gamle sider'),
    'page callback'    => 'drupal_get_form',
    'access callback'  => '_os2web_old_nodes_menu_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Access callback to access a user to the page.
 */
function _os2web_old_nodes_menu_access($account) {
  global $user;

  return $user->uid == $account->uid && user_access('access old nodes page');
}

/**
 * Implements hook_permission().
 */
function os2web_old_nodes_permission() {
  return array(
    'access old nodes page' => array(
      'title' => t('Access OS2web Old Nodes page'),
    ),
  );
}
